// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWgIRze1F7A-KZcmym26I49jZPk8aGjt4',
    appId: '1:939185606946:web:0f62e95a807650c6cb557b',
    messagingSenderId: '939185606946',
    projectId: 'selfmess-3a812',
    authDomain: 'selfmess-3a812.firebaseapp.com',
    storageBucket: 'selfmess-3a812.firebasestorage.app',
    measurementId: 'G-CTM053Q92S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUEStOXx8Swe6w9zyqfnrQ8UyXWtVBT_g',
    appId: '1:939185606946:android:f5387588804f93c1cb557b',
    messagingSenderId: '939185606946',
    projectId: 'selfmess-3a812',
    storageBucket: 'selfmess-3a812.firebasestorage.app',
  );
}
